### PR TITLE
Fix Git dependencies.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by fanzeyi** [comment]
Hello!

Thanks for the pull request. Can you give me a little description on what issue this pull request is trying to solve? I tested locally with specifying a git dependency and it seems to be working fine. The file I used for testing:

```rust
//# tuple-combinator = { git = "https://github.com/fanzeyi/tuple-combinator.git" }

use tuple_combinator::TupleCombinator;

fn main() {
    let a = (Some(1), Some(2));
    let b = a.map(|(x, y)| x + y);

    println!("{:?}", b);
}
```

**Comment by reitermarkus** [comment]
If you have multiple dependencies, the non-string ones apparently have to be serialised last, otherwise you get a `ValueAfterTable` error.

**Comment by fanzeyi** [comment]
@reitermarkus The closest I can get is:

```//# [tuple-combinator]
//# git = "https://github.com/fanzeyi/tuple-combinator.git"

use tuple_combinator::TupleCombinator;

fn main() {
    let a = (Some(1), Some(2));
    let b = a.map(|(x, y)| x + y);

    println!("{:?}", b);
}
```

which does not make sense to me. Can you give me an example? Thanks!

**Comment by fanzeyi** [comment]
Anyway, I'm going to merge this since it doesn't really bring any harm. It would be great if you can give me an example so I can add it to the test suite.

**Comment by reitermarkus** [comment]
Well, this is pretty weird. It seems to be related to the dependency starting with `d`.

Try:

```rust
//# rand = "0.5.0"
//# duple-combinator = { git = "https://github.com/fanzeyi/tuple-combinator.git" }

fn main() {
  println!("Hello, world!");
}
```

**Comment by fanzeyi** [comment]
@reitermarkus haha I see. Thanks for the example & the pull request. I'll add this to the test cases and make a release.

**Pull request merged**
